dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -e .
  - pip install -r requirements.txt
script: 
  - curl $USER_YAML_URL > user.yaml
  - pytest
  - chmod +x tests/bash_tests.sh
  - ./tests/bash_tests.sh
