dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -e .
  - pip install -r requirements.txt
script:
  #Download user.yaml file from a super secret URL that we enter as a Travis Environment variable
  - curl $USER_YAML_URL > user.yaml
  #Runs tests of specific functions nicely (see tests/*.py)
  - pytest
  #A bash script handles the rest so this file doesn't get too messy
  - chmod +x tests/bash_tests.sh
  - ./tests/bash_tests.sh
